name: Build MT4 Watcher EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile scripts\mt4_watcher.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mt4_watcher-exe
          path: dist\mt4_watcher.exe
